### ISSUE TITLE
Where you download nightly

### ISSUE THREAD

**Issue by CrazyBaran** [voltage220/AspNetCore_OData_v7b1#1]
Could you explain me how to download via nuget nightly build of AspNetCore.Odata?

**Comment by Julian-Chu** [comment]
@CrazyBaran 
in Package Manager Console:
`Install-Package Microsoft.AspNetCore.OData -Version 7.0.0-Nightly201801221342 -Source https://www.myget.org/F/webapinetcore/api/v3/index.json`

more nightly build: [link](https://www.myget.org/F/webapinetcore/Packages?$select=Id,Version&$orderby=Version%20desc&$top=10&$format=application/json)
